

micro_category_dict={}
"""

file=open("micro.txt")

index=1
for line in file:
    if line !="\n":
        line=line.strip("\n")
        line=line.rstrip()
        micro_category_dict.update({line:index})
    else:
        index+=1

for item in micro_category_dict:
    print(item)

print(micro_category_dict.keys())

print(micro_category_dict.values())

file_1=open("micro_category.txt",mode="a+")

file_1.write(str(micro_category_dict))

"""
micro_category_dict_final={'branch-instructions': 3, 'branch-misses': 3, 'bus-cycles': 3, 'cache-misses': 3, 'cache-references': 3, 'cpu-cycles': 3, 'instructions': 3, 'ref-cycles': 3, 'alignment-faults': 1, 'bpf-output': 1, 'context-switches': 1, 'cpu-clock': 1, 'cpu-migrations': 1, 'dummy': 1, 'emulation-faults': 1, 'major-faults': 1, 'minor-faults': 1, 'page-faults': 1, 'task-clock': 1, 'L1-dcache-load-misses': 2, 'L1-dcache-loads': 2, 'L1-dcache-stores': 2, 'L1-icache-load-misses': 2, 'LLC-load-misses': 2, 'LLC-loads': 2, 'LLC-store-misses': 2, 'LLC-stores': 2, 'branch-load-misses': 2, 'branch-loads': 2, 'dTLB-load-misses': 2, 'dTLB-loads': 2, 'dTLB-store-misses': 2, 'dTLB-stores': 2, 'iTLB-load-misses': 2, 'iTLB-loads': 2, 'node-load-misses': 2, 'node-loads': 2, 'node-store-misses': 2, 'node-stores': 2, 'cstate_core/c3-residency/': 3, 'cstate_core/c6-residency/': 3, 'cstate_core/c7-residency/': 3, 'cstate_pkg/c2-residency/': 3, 'cstate_pkg/c3-residency/': 3, 'cstate_pkg/c6-residency/': 3, 'cstate_pkg/c7-residency/': 3, 'intel_bts//': 3, 'intel_pt//': 3, 'mem-loads': 3, 'mem-stores': 3, 'msr/aperf/': 3, 'msr/cpu_thermal_margin/': 3, 'msr/mperf/': 3, 'msr/pperf/': 3, 'msr/smi/': 3, 'msr/tsc/': 3, 'power/energy-pkg/': 3, 'power/energy-ram/': 3, 'topdown-fetch-bubbles': 3, 'topdown-recovery-bubbles': 3, 'topdown-slots-issued': 3,
                     'topdown-slots-retired': 3, 'topdown-total-slots': 3, 'uncore_iio_free_running_0/bw_in_port0/': 3, 'uncore_iio_free_running_0/bw_in_port1/': 3, 'uncore_iio_free_running_0/bw_in_port2/': 3, 'uncore_iio_free_running_0/bw_in_port3/': 3, 'uncore_iio_free_running_0/bw_out_port0/': 3, 'uncore_iio_free_running_0/bw_out_port1/': 3, 'uncore_iio_free_running_0/bw_out_port2/': 3, 'uncore_iio_free_running_0/bw_out_port3/': 3, 'uncore_iio_free_running_0/ioclk/': 3, 'uncore_iio_free_running_0/util_in_port0/': 3, 'uncore_iio_free_running_0/util_in_port1/': 3, 'uncore_iio_free_running_0/util_in_port2/': 3, 'uncore_iio_free_running_0/util_in_port3/': 3, 'uncore_iio_free_running_0/util_out_port0/': 3, 'uncore_iio_free_running_0/util_out_port1/': 3, 'uncore_iio_free_running_0/util_out_port2/': 3, 'uncore_iio_free_running_0/util_out_port3/': 3, 'uncore_iio_free_running_1/bw_in_port0/': 3, 'uncore_iio_free_running_1/bw_in_port1/': 3, 'uncore_iio_free_running_1/bw_in_port2/': 3, 'uncore_iio_free_running_1/bw_in_port3/': 3, 'uncore_iio_free_running_1/bw_out_port0/': 3, 'uncore_iio_free_running_1/bw_out_port1/': 3, 'uncore_iio_free_running_1/bw_out_port2/': 3,
                     'uncore_iio_free_running_1/bw_out_port3/': 3, 'uncore_iio_free_running_1/ioclk/': 3, 'uncore_iio_free_running_1/util_in_port0/': 3, 'uncore_iio_free_running_1/util_in_port1/': 3, 'uncore_iio_free_running_1/util_in_port2/': 3, 'uncore_iio_free_running_1/util_in_port3/': 3, 'uncore_iio_free_running_1/util_out_port0/': 3, 'uncore_iio_free_running_1/util_out_port1/': 3, 'uncore_iio_free_running_1/util_out_port2/': 3, 'uncore_iio_free_running_1/util_out_port3/': 3, 'uncore_iio_free_running_2/bw_in_port0/': 3, 'uncore_iio_free_running_2/bw_in_port1/': 3, 'uncore_iio_free_running_2/bw_in_port2/': 3, 'uncore_iio_free_running_2/bw_in_port3/': 3, 'uncore_iio_free_running_2/bw_out_port0/': 3, 'uncore_iio_free_running_2/bw_out_port1/': 3, 'uncore_iio_free_running_2/bw_out_port2/': 3, 'uncore_iio_free_running_2/bw_out_port3/': 3, 'uncore_iio_free_running_2/ioclk/': 3, 'uncore_iio_free_running_2/util_in_port0/': 3, 'uncore_iio_free_running_2/util_in_port1/': 3, 'uncore_iio_free_running_2/util_in_port2/': 3, 'uncore_iio_free_running_2/util_in_port3/': 3, 'uncore_iio_free_running_2/util_out_port0/': 3, 'uncore_iio_free_running_2/util_out_port1/': 3, 'uncore_iio_free_running_2/util_out_port2/': 3, 'uncore_iio_free_running_2/util_out_port3/': 3, 'uncore_iio_free_running_3/bw_in_port0/': 3, 'uncore_iio_free_running_3/bw_in_port1/': 3, 'uncore_iio_free_running_3/bw_in_port2/': 3, 'uncore_iio_free_running_3/bw_in_port3/': 3, 'uncore_iio_free_running_3/bw_out_port0/': 3, 'uncore_iio_free_running_3/bw_out_port1/': 3, 'uncore_iio_free_running_3/bw_out_port2/': 3,
                     'uncore_iio_free_running_3/bw_out_port3/': 3, 'uncore_iio_free_running_3/ioclk/': 3, 'uncore_iio_free_running_3/util_in_port0/': 3, 'uncore_iio_free_running_3/util_in_port1/': 3, 'uncore_iio_free_running_3/util_in_port2/': 3, 'uncore_iio_free_running_3/util_in_port3/': 3, 'uncore_iio_free_running_3/util_out_port0/': 3, 'uncore_iio_free_running_3/util_out_port1/': 3, 'uncore_iio_free_running_3/util_out_port2/': 3, 'uncore_iio_free_running_3/util_out_port3/': 3, 'uncore_iio_free_running_4/bw_in_port0/': 3, 'uncore_iio_free_running_4/bw_in_port1/': 3, 'uncore_iio_free_running_4/bw_in_port2/': 3, 'uncore_iio_free_running_4/bw_in_port3/': 3, 'uncore_iio_free_running_4/bw_out_port0/': 3, 'uncore_iio_free_running_4/bw_out_port1/': 3, 'uncore_iio_free_running_4/bw_out_port2/': 3, 'uncore_iio_free_running_4/bw_out_port3/': 3, 'uncore_iio_free_running_4/ioclk/': 3, 'uncore_iio_free_running_4/util_in_port0/': 3, 'uncore_iio_free_running_4/util_in_port1/': 3, 'uncore_iio_free_running_4/util_in_port2/': 3, 'uncore_iio_free_running_4/util_in_port3/': 3, 'uncore_iio_free_running_4/util_out_port0/': 3, 'uncore_iio_free_running_4/util_out_port1/': 3, 'uncore_iio_free_running_4/util_out_port2/': 3, 'uncore_iio_free_running_4/util_out_port3/': 3, 'uncore_iio_free_running_5/bw_in_port0/': 3, 'uncore_iio_free_running_5/bw_in_port1/': 3, 'uncore_iio_free_running_5/bw_in_port2/': 3, 'uncore_iio_free_running_5/bw_in_port3/': 3, 'uncore_iio_free_running_5/bw_out_port0/': 3, 'uncore_iio_free_running_5/bw_out_port1/': 3, 'uncore_iio_free_running_5/bw_out_port2/': 3,
                     'uncore_iio_free_running_5/bw_out_port3/': 3, 'uncore_iio_free_running_5/ioclk/': 3, 'uncore_iio_free_running_5/util_in_port0/': 3, 'uncore_iio_free_running_5/util_in_port1/': 3, 'uncore_iio_free_running_5/util_in_port2/': 3, 'uncore_iio_free_running_5/util_in_port3/': 3, 'uncore_iio_free_running_5/util_out_port0/': 3, 'uncore_iio_free_running_5/util_out_port1/': 3, 'uncore_iio_free_running_5/util_out_port2/': 3, 'uncore_iio_free_running_5/util_out_port3/': 3, 'uncore_imc_0/cas_count_read/': 3, 'uncore_imc_0/cas_count_write/': 3, 'uncore_imc_0/clockticks/': 3, 'uncore_imc_1/cas_count_read/': 3, 'uncore_imc_1/cas_count_write/': 3, 'uncore_imc_1/clockticks/': 3, 'uncore_imc_2/cas_count_read/': 3, 'uncore_imc_2/cas_count_write/': 3, 'uncore_imc_2/clockticks/': 3, 'uncore_imc_3/cas_count_read/': 3, 'uncore_imc_3/cas_count_write/': 3,
                     'uncore_imc_3/clockticks/': 3, 'uncore_imc_4/cas_count_read/': 3, 'uncore_imc_4/cas_count_write/': 3, 'uncore_imc_4/clockticks/': 3, 'uncore_imc_5/cas_count_read/': 3, 'uncore_imc_5/cas_count_write/': 3, 'uncore_imc_5/clockticks/': 3, 'l1d.replacement': 4, 'l1d_pend_miss.fb_full': 4, 'l1d_pend_miss.pending': 4, 'l1d_pend_miss.pending_cycles': 4, 'l1d_pend_miss.pending_cycles_any': 4, 'l2_lines_in.all': 4, 'l2_lines_out.non_silent': 4, 'l2_lines_out.silent': 4, 'l2_lines_out.useless_hwpf': 4, 'l2_rqsts.all_code_rd': 4, 'l2_rqsts.all_demand_data_rd': 4, 'l2_rqsts.all_demand_miss': 4, 'l2_rqsts.all_demand_references': 4, 'l2_rqsts.all_pf': 4, 'l2_rqsts.all_rfo': 4, 'l2_rqsts.code_rd_hit': 4, 'l2_rqsts.code_rd_miss': 4, 'l2_rqsts.demand_data_rd_hit': 4, 'l2_rqsts.demand_data_rd_miss': 4, 'l2_rqsts.miss': 4, 'l2_rqsts.pf_hit': 4, 'l2_rqsts.pf_miss': 4, 'l2_rqsts.references': 4, 'l2_rqsts.rfo_hit': 4, 'l2_rqsts.rfo_miss': 4, 'l2_trans.l2_wb': 4, 'longest_lat_cache.miss': 4, 'longest_lat_cache.reference': 4, 'mem_inst_retired.all_loads': 4, 'mem_inst_retired.all_stores': 4, 'mem_inst_retired.lock_loads': 4, 'mem_inst_retired.split_loads': 4, 'mem_inst_retired.split_stores': 4, 'mem_inst_retired.stlb_miss_loads': 4,
                     'mem_inst_retired.stlb_miss_stores': 4, 'mem_load_l3_hit_retired.xsnp_hit': 4, 'mem_load_l3_hit_retired.xsnp_hitm': 4, 'mem_load_l3_hit_retired.xsnp_miss': 4, 'mem_load_l3_hit_retired.xsnp_none': 4, 'mem_load_l3_miss_retired.local_dram': 4, 'mem_load_l3_miss_retired.remote_dram': 4, 'mem_load_l3_miss_retired.remote_fwd': 4, 'mem_load_l3_miss_retired.remote_hitm': 4, 'mem_load_l3_miss_retired.remote_pmm': 4, 'mem_load_misc_retired.uc': 4, 'mem_load_retired.fb_hit': 4, 'mem_load_retired.l1_hit': 4, 'mem_load_retired.l1_miss': 4, 'mem_load_retired.l2_hit': 4, 'mem_load_retired.l2_miss': 4, 'mem_load_retired.l3_hit': 4, 'mem_load_retired.l3_miss': 4, 'mem_load_retired.local_pmm': 4, 'offcore_requests.all_data_rd': 4, 'offcore_requests.all_requests': 4, 'offcore_requests.demand_code_rd': 4, 'offcore_requests.demand_data_rd': 4, 'offcore_requests.demand_rfo': 4, 'offcore_requests_buffer.sq_full': 4, 'offcore_requests_outstanding.all_data_rd': 4, 'offcore_requests_outstanding.cycles_with_data_rd': 4, 'offcore_requests_outstanding.cycles_with_demand_code_rd': 4, 'offcore_requests_outstanding.cycles_with_demand_data_rd': 4, 'offcore_requests_outstanding.cycles_with_demand_rfo': 4, 'offcore_requests_outstanding.demand_code_rd': 4, 'offcore_requests_outstanding.demand_data_rd': 4,
                     'offcore_requests_outstanding.demand_data_rd_ge_6': 4, 'offcore_requests_outstanding.demand_rfo': 4, 'offcore_response': 4, 'sq_misc.split_lock': 4, 'fp_arith_inst_retired.128b_packed_double': 5, 'fp_arith_inst_retired.128b_packed_single': 5, 'fp_arith_inst_retired.256b_packed_double': 5, 'fp_arith_inst_retired.256b_packed_single': 5, 'fp_arith_inst_retired.512b_packed_double': 5, 'fp_arith_inst_retired.512b_packed_single': 5, 'fp_arith_inst_retired.scalar_double': 5, 'fp_arith_inst_retired.scalar_single': 5, 'fp_assist.any': 5, 'dsb2mite_switches.penalty_cycles': 6, 'frontend_retired.dsb_miss': 6, 'frontend_retired.itlb_miss': 6, 'frontend_retired.l1i_miss': 6, 'frontend_retired.l2_miss': 6, 'frontend_retired.latency_ge_128': 6, 'frontend_retired.latency_ge_16': 6, 'frontend_retired.latency_ge_2': 6, 'frontend_retired.latency_ge_256': 6, 'frontend_retired.latency_ge_2_bubbles_ge_1': 6, 'frontend_retired.latency_ge_2_bubbles_ge_2': 6, 'frontend_retired.latency_ge_2_bubbles_ge_3': 6, 'frontend_retired.latency_ge_32': 6, 'frontend_retired.latency_ge_4': 6, 'frontend_retired.latency_ge_512': 6, 'frontend_retired.latency_ge_64': 6, 'frontend_retired.latency_ge_8': 6, 'frontend_retired.stlb_miss': 6, 'icache_16b.ifdata_stall': 6, 'icache_64b.iftag_hit': 6, 'icache_64b.iftag_miss': 6,
                     'icache_64b.iftag_stall': 6, 'idq.all_dsb_cycles_4_uops': 6, 'idq.all_dsb_cycles_any_uops': 6, 'idq.all_mite_cycles_4_uops': 6, 'idq.all_mite_cycles_any_uops': 6, 'idq.dsb_cycles': 6, 'idq.dsb_uops': 6, 'idq.mite_cycles': 6, 'idq.mite_uops': 6, 'idq.ms_cycles': 6, 'idq.ms_dsb_cycles': 6, 'idq.ms_mite_uops': 6, 'idq.ms_switches': 6, 'idq.ms_uops': 6, 'idq_uops_not_delivered.core': 6, 'idq_uops_not_delivered.cycles_0_uops_deliv.core': 6, 'idq_uops_not_delivered.cycles_fe_was_ok': 6, 'idq_uops_not_delivered.cycles_le_1_uop_deliv.core': 6, 'idq_uops_not_delivered.cycles_le_2_uop_deliv.core': 6, 'idq_uops_not_delivered.cycles_le_3_uop_deliv.core': 6, 'cycle_activity.cycles_l3_miss': 7, 'cycle_activity.stalls_l3_miss': 7, 'hle_retired.aborted': 7, 'hle_retired.aborted_events': 7, 'hle_retired.aborted_mem': 7, 'hle_retired.aborted_memtype': 7, 'hle_retired.aborted_timer': 7, 'hle_retired.aborted_unfriendly': 7, 'hle_retired.commit': 7, 'hle_retired.start': 7, 'machine_clears.memory_ordering': 7, 'mem_trans_retired.load_latency_gt_128': 7, 'mem_trans_retired.load_latency_gt_16': 7, 'mem_trans_retired.load_latency_gt_256': 7, 'mem_trans_retired.load_latency_gt_32': 7, 'mem_trans_retired.load_latency_gt_4': 7, 'mem_trans_retired.load_latency_gt_512': 7,
                     'mem_trans_retired.load_latency_gt_64': 7, 'mem_trans_retired.load_latency_gt_8': 7, 'offcore_requests.l3_miss_demand_data_rd': 7,
                     'offcore_requests_outstanding.cycles_with_l3_miss_demand_data_rd': 7, 'offcore_requests_outstanding.l3_miss_demand_data_rd': 7, 'offcore_requests_outstanding.l3_miss_demand_data_rd_ge_6': 7, 'rtm_retired.aborted': 7, 'rtm_retired.aborted_events': 7, 'rtm_retired.aborted_mem': 7, 'rtm_retired.aborted_memtype': 7, 'rtm_retired.aborted_timer': 7, 'rtm_retired.aborted_unfriendly': 7, 'rtm_retired.commit': 7, 'rtm_retired.start': 7, 'tx_exec.misc1': 7, 'tx_exec.misc2': 7, 'tx_exec.misc3': 7, 'tx_exec.misc4': 7, 'tx_exec.misc5': 7, 'tx_mem.abort_capacity': 7, 'tx_mem.abort_conflict': 7, 'tx_mem.abort_hle_elision_buffer_mismatch': 7, 'tx_mem.abort_hle_elision_buffer_not_empty': 7, 'tx_mem.abort_hle_elision_buffer_unsupported_alignment': 7, 'tx_mem.abort_hle_store_to_elided_lock': 7, 'tx_mem.hle_elision_buffer_full': 7, 'core_power.lvl0_turbo_license': 8, 'core_power.lvl1_turbo_license': 8, 'core_power.lvl2_turbo_license': 8, 'core_power.throttle': 8, 'core_snoop_response.rsp_ifwdfe': 8, 'core_snoop_response.rsp_ifwdm': 8, 'core_snoop_response.rsp_ihitfse': 8, 'core_snoop_response.rsp_ihiti': 8, 'core_snoop_response.rsp_sfwdfe': 8, 'core_snoop_response.rsp_sfwdm': 8, 'core_snoop_response.rsp_shitfse': 8, 'hw_interrupts.received': 8, 'idi_misc.wb_downgrade': 8, 'idi_misc.wb_upgrade': 8, 'memory_disambiguation.history_reset': 8, 'sw_prefetch_access.nta': 8, 'sw_prefetch_access.prefetchw': 8, 'sw_prefetch_access.t0': 8, 'sw_prefetch_access.t1_t2': 8, 'arith.divider_active': 9, 'baclears.any': 9,
                     'br_inst_retired.all_branches': 9, 'br_inst_retired.all_branches_pebs': 9, 'br_inst_retired.conditional': 9, 'br_inst_retired.far_branch': 9, 'br_inst_retired.near_call': 9, 'br_inst_retired.near_return': 9, 'br_inst_retired.near_taken': 9, 'br_inst_retired.not_taken': 9, 'br_misp_retired.all_branches': 9, 'br_misp_retired.all_branches_pebs': 9, 'br_misp_retired.conditional': 9, 'br_misp_retired.near_call': 9, 'br_misp_retired.near_taken': 9, 'cpu_clk_thread_unhalted.one_thread_active': 9, 'cpu_clk_thread_unhalted.ref_xclk': 9, 'cpu_clk_thread_unhalted.ref_xclk_any': 9, 'cpu_clk_unhalted.one_thread_active': 9, 'cpu_clk_unhalted.ref_tsc': 9, 'cpu_clk_unhalted.ref_xclk': 9, 'cpu_clk_unhalted.ref_xclk_any': 9, 'cpu_clk_unhalted.ring0_trans': 9, 'cpu_clk_unhalted.thread': 9, 'cpu_clk_unhalted.thread_any': 9, 'cpu_clk_unhalted.thread_p': 9, 'cpu_clk_unhalted.thread_p_any': 9, 'cycle_activity.cycles_l1d_miss': 9, 'cycle_activity.cycles_l2_miss': 9, 'cycle_activity.cycles_mem_any': 9, 'cycle_activity.stalls_l1d_miss': 9, 'cycle_activity.stalls_l2_miss': 9, 'cycle_activity.stalls_mem_any': 9, 'cycle_activity.stalls_total': 9, 'exe_activity.1_ports_util': 9, 'exe_activity.2_ports_util': 9, 'exe_activity.3_ports_util': 9, 'exe_activity.4_ports_util': 9, 'exe_activity.bound_on_stores': 9, 'exe_activity.exe_bound_0_ports': 9, 'ild_stall.lcp': 9, 'inst_retired.any': 9, 'inst_retired.any_p': 9, 'inst_retired.prec_dist': 9,
                     'inst_retired.total_cycles_ps': 9, 'int_misc.clear_resteer_cycles': 9, 'int_misc.recovery_cycles': 9, 'int_misc.recovery_cycles_any': 9, 'ld_blocks.no_sr': 9, 'ld_blocks.store_forward': 9, 'ld_blocks_partial.address_alias': 9, 'load_hit_pre.sw_pf': 9, 'lsd.cycles_4_uops': 9, 'lsd.cycles_active': 9, 'lsd.uops': 9, 'machine_clears.count': 9, 'machine_clears.smc': 9, 'other_assists.any': 9, 'partial_rat_stalls.scoreboard': 9, 'resource_stalls.any': 9, 'resource_stalls.sb': 9, 'rob_misc_events.lbr_inserts': 9, 'rob_misc_events.pause_inst': 9, 'rs_events.empty_cycles': 9, 'rs_events.empty_end': 9, 'uops_dispatched_port.port_0': 9, 'uops_dispatched_port.port_1': 9, 'uops_dispatched_port.port_2': 9, 'uops_dispatched_port.port_3': 9, 'uops_dispatched_port.port_4': 9, 'uops_dispatched_port.port_5': 9, 'uops_dispatched_port.port_6': 9, 'uops_dispatched_port.port_7': 9, 'uops_executed.core': 9, 'uops_executed.core_cycles_ge_1': 9,
                     'uops_executed.core_cycles_ge_2': 9, 'uops_executed.core_cycles_ge_3': 9, 'uops_executed.core_cycles_ge_4': 9, 'uops_executed.core_cycles_none': 9, 'uops_executed.cycles_ge_1_uop_exec': 9, 'uops_executed.cycles_ge_2_uops_exec': 9, 'uops_executed.cycles_ge_3_uops_exec': 9, 'uops_executed.cycles_ge_4_uops_exec': 9, 'uops_executed.stall_cycles': 9, 'uops_executed.thread': 9, 'uops_executed.x87': 9, 'uops_issued.any': 9, 'uops_issued.slow_lea': 9, 'uops_issued.stall_cycles': 9, 'uops_issued.vector_width_mismatch': 9, 'uops_retired.retire_slots': 9, 'uops_retired.stall_cycles': 9, 'uops_retired.total_cycles': 9, 'dtlb_load_misses.miss_causes_a_walk': 10, 'dtlb_load_misses.stlb_hit': 10, 'dtlb_load_misses.walk_active': 10, 'dtlb_load_misses.walk_completed': 10, 'dtlb_load_misses.walk_completed_1g': 10, 'dtlb_load_misses.walk_completed_2m_4m': 10, 'dtlb_load_misses.walk_completed_4k': 10, 'dtlb_load_misses.walk_pending': 10, 'dtlb_store_misses.miss_causes_a_walk': 10, 'dtlb_store_misses.stlb_hit': 10, 'dtlb_store_misses.walk_active': 10, 'dtlb_store_misses.walk_completed': 10, 'dtlb_store_misses.walk_completed_1g': 10, 'dtlb_store_misses.walk_completed_2m_4m': 10, 'dtlb_store_misses.walk_completed_4k': 10, 'dtlb_store_misses.walk_pending': 10, 'ept.walk_pending': 10, 'itlb.itlb_flush': 10, 'itlb_misses.miss_causes_a_walk': 10,
                     'itlb_misses.stlb_hit': 10, 'itlb_misses.walk_active': 10, 'itlb_misses.walk_completed': 10, 'itlb_misses.walk_completed_1g': 10, 'itlb_misses.walk_completed_2m_4m': 10, 'itlb_misses.walk_completed_4k': 10, 'itlb_misses.walk_pending': 10, 'tlb_flush.dtlb_thread': 10, 'tlb_flush.stlb_any': 10}